------ JOINS IN SQL ---
--- JOINS IN SQL IS USED FOR LINKING TWO OR MORE TABLES IF THEY HAVE A SAME OR COMMON COLUMN . FOREIGN KEY IS NOT NECESSARY FOR JOINS . 
--- TYPES OF JOINS : INNER JOIN , LEFT OUTER JOIN , RIGHT OUTER JOIN , SELF JOIN , CROSS JOIN ----

CREATE DATABASE IF NOT EXISTS ecom ;
use ecom ;
CREATE TABLE IF NOT EXISTS customers( id INT PRIMARY KEY , name VARCHAR(100) ) ;
CREATE TABLE IF NOT EXISTS orderes( id INT PRIMARY KEY , order_name VARCHAR(100) );
INSERT INTO customers(id , name ) VALUES ( 1 , 'SAPTA') , ( 2 , ' ANU' ) , ( 3 , 'ANUSKA') , ( 4 , 'ANUSKA BABY'), ( 5 , 'PORI') ;
SELECT * from customers ;
INSERT INTO orderes (id , order_name) VALUES ( 1, 'CONDOM') , ( 2 , 'DILDO') , ( 3 , 'PUSSY') , ( 6 , 'FLUID GEL') , ( 7 , 'VIBRATOR') ;
SELECT * from orderes;


--- INNER JOIN : USED IN GETTING THE ROWS THAT HAVE THE SAME MATCHING VALUES IN BOTH THE TABLES . i.e : INTERSECTION OF BOTH TABLES -- 

SELECT * from customers INNER JOIN orderes ON customers.id = orderes.id;


---- LEFT JOIN : USED FOR GETTING ALL THE ROWS FROM THE LEFT TABLE ALONG WITH THE MATCHING VALUES FROM THE RIGHT TABLE . IF ANY ROW DOESNOT HAVE
---- A MATCH FROM THE RIGHT TABLE THEN THAT COLUMN IN RIGHT TABLE IS SET TO BE NULL .
---- LEFT TABLE => BEFORE LEFT JOIN KEYWORD , RIGHT TABLE => AFTER LEFT JOIN KEYWORD 


SELECT * from customers LEFT JOIN orderes ON customers.id = orderes.id;
SELECT * from orderes LEFT JOIN customers ON orderes.id = customers.id ;


----- RIGHT JOIN : USED FOR GETTING ALL THE ROWS FROM THE RIGHT TABLE ALONG WITH THE MATCHING  VALUES FROM THE LEFT TABLE . IF ANY ROW DOESNOT HAVE
---- A MATCH FROM THE LEFT TABLE THEN THAT COLUMN IN THE LEFT TABLE IS SET TO BE NULL . LEFT TABLE => LEFT OF RIGHT JOIN KEYWORD , RIGHT TABLE => RIGHT OF JOIN KEYWORD

SELECT * from customers RIGHT JOIN orderes ON customers.id = orderes.id;
SELECT * from orderes RIGHT JOIN customers ON customers.id = orderes.id ;